### PR TITLE
refactor(GRO-2157): validation on addressdto date fields and new clas…

### PR DESCRIPTION
**Pull request by WeiLu1**
…s validator for previous address dates

#### Description
Change the data type for `toDate` and `fromDate` in the `addressDto` from `String` to `LocalDate`. 

Add new class validator such that if the address is of type `previous` then the `fromDate` must be before the `toDate`. 

Add extra configuration to object mapper to account for `LocalDate`.

Add and amend unit tests. 

#### Background Context
Part of the work to fix the aggregator bugs before launch.

### CODE REVIEW

**Comment by selina-bot-user** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **weilu1**
You can assign the PR to them by writing `/assign @weilu1` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=Selina-Finance%2Fms-lending-api).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/Selina-Finance/ms-lending-api/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by selina-bot-user** [comment]
:star: PR built and available in a preview **jx-selina-finance-ms-lending-api-pr-191** [here](http://ms-lending-api-pr191.selinadev.co.uk)

**Comment by angelo-paiva-ptech** [comment]
Code doesn't look bad. My only comment is that I'd prefer if it were more generic.

So instead of being made specifically for `AddressDto`, it could be applied to any object. And maybe it could be called something like 

```java

@DateIsAfter(date = "fromDate")
LocalDate toDate;

LocalDate fromDate;
```

I'd like to hear the opinions of the other guys.

**Comment by KastorDriver** [comment]
@angelo-paiva-ptech your [comment](https://github.com/Selina-Finance/ms-lending-api/pull/191#issuecomment-1607397014) makes sense!

The reason why our custom annotation `MoveOutAfterMoveInDate` should be a class level, but not a class property level is we need to know about other DTO's properties to check if the "toDate" is correct.

Please, pay attention that in the custom validator, we get the whole `AddressDto` object, so we can get access to the "fromDate", "toDate", and any other fields if we need.

But if the annotation was only class property level we could operate only with one LocalDate "toDate" and there is no way to get the value of other fields such as LocalDate "fromDate".

**Comment by selina-bot-user** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[KastorDriver](https://github.com/Selina-Finance/ms-lending-api/pull/191#issuecomment-1607468180 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=Selina-Finance%2Fms-lending-api).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/Selina-Finance/ms-lending-api/blob/main/OWNERS)~~ [KastorDriver]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
