### PR TITLE
refactor(GRO-2208): add broker fee fields to QQ request and flow

### PR DESCRIPTION
**Pull request by WeiLu1**
#### Description
Add broker fee fields to QQ request body and subsequent request bodies downstream to selection service and middleware.

#### Background Context
Part of the work to launch aggregators.

### CODE REVIEW

**Comment by selina-bot-user** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **weilu1**
You can assign the PR to them by writing `/assign @weilu1` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=Selina-Finance%2Fms-lending-api).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/Selina-Finance/ms-lending-api/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by selina-bot-user** [comment]
:star: PR built and available in a preview **jx-selina-finance-ms-lending-api-pr-193** [here](http://ms-lending-api-pr193.selinadev.co.uk)

**Review by angelo-paiva-ptech — APPROVED** [review]

**Comment by selina-bot-user** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[angelo-paiva-ptech](https://github.com/Selina-Finance/ms-lending-api/pull/193#pullrequestreview-1504889479 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=Selina-Finance%2Fms-lending-api).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/Selina-Finance/ms-lending-api/blob/main/OWNERS)~~ [angelo-paiva-ptech]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by selina-bot-user** [comment]
@WeiLu1: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | d4525b0779cf6e5faf23fdbfa46d816c9868ace6 | [link](http://dashboard-jx.selinadev.co.uk/namespaces/jx/pipelineruns/finance-ms-lending-api-pr-193-pr-pz9c8) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by selina-bot-user** [comment]
:star: PR built and available in a preview **jx-selina-finance-ms-lending-api-pr-193** [here](http://ms-lending-api-pr193.selinadev.co.uk)

**Comment by selina-bot-user** [comment]
:star: PR built and available in a preview **jx-selina-finance-ms-lending-api-pr-193** [here](http://ms-lending-api-pr193.selinadev.co.uk)

**Comment by selina-bot-user** [comment]
:star: PR built and available in a preview **jx-selina-finance-ms-lending-api-pr-193** [here](http://ms-lending-api-pr193.selinadev.co.uk)

**Comment by selina-bot-user** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[angelo-paiva-ptech](https://github.com/Selina-Finance/ms-lending-api/pull/193#pullrequestreview-1504889479 "Approved")*, *[KastorDriver](https://github.com/Selina-Finance/ms-lending-api/pull/193#issuecomment-1613920659 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=Selina-Finance%2Fms-lending-api).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/Selina-Finance/ms-lending-api/blob/main/OWNERS)~~ [KastorDriver,angelo-paiva-ptech]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by selina-bot-user** [comment]
:star: PR built and available in a preview **jx-selina-finance-ms-lending-api-pr-193** [here](http://ms-lending-api-pr193.selinadev.co.uk)

**Pull request merged**
