### PR TITLE
GRO-2471: Disable CSRF protection

### PR DESCRIPTION
**Pull request by KastorDriver**
[GRO-2471](https://selina.atlassian.net/browse/GRO-2471)
The Lending API requires a CSRF token in case of a request without an Authorization header

```
{
    "title": "Forbidden",
    "status": 403,
    "detail": "Could not verify the provided CSRF token because no token was found to compare."
}
```
However, in that case, a response should be Unauthorized, but not Forbidden.

That happens because in security settings the CSRF protection is enabled. Since the service does not provide any web pages and is supposed to be called only by other services there is no need to have a CSRF protection at all.

The correct response should be
```
{
    "title": "Unauthorized",
    "status": 401,
    "detail": "Full authentication is required to access this resource"
}
```

[GRO-2471]: https://selina.atlassian.net/browse/GRO-2471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by selina-bot-user** [comment]
[jx-info] Hi, we've detected that the pipelines in this repository are using a syntax that will soon be deprecated.
We'll continue to update you through PRs as we progress. Please check [#8589](https://www.github.com/jenkins-x/jx/issues/8589) for further information.

**Comment by selina-bot-user** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **kastordriver**
You can assign the PR to them by writing `/assign @kastordriver` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=Selina-Finance%2Fms-lending-api).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/Selina-Finance/ms-lending-api/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by selina-bot-user** [comment]
:star: PR built and available in a preview **jx-selina-finance-ms-lending-api-pr-212** [here](http://ms-lending-api-pr212.selinadev.co.uk)

**Comment by selina-bot-user** [comment]
:star: PR built and available in a preview **jx-selina-finance-ms-lending-api-pr-212** [here](http://ms-lending-api-pr212.selinadev.co.uk)

**Review by angelo-paiva-ptech — APPROVED** [review]

**Comment by selina-bot-user** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[angelo-paiva-ptech](https://github.com/Selina-Finance/ms-lending-api/pull/212#pullrequestreview-1599847978 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=Selina-Finance%2Fms-lending-api).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/Selina-Finance/ms-lending-api/blob/main/OWNERS)~~ [angelo-paiva-ptech]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
